version: '3.8'

services:
  vue3-template:
    container_name: vue3-template
    build:
      dockerfile: ci/Dockerfile.dev
    ports:
      - "${PORT}:${PORT}"
      - "${HMR_PORT}:24678"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    command: pnpm dev
    platform: linux/amd64
    networks:
      - app-net

networks:
  app-net:
    external: true